# Generated by Django 3.1.7 on 2021-04-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20)),
                ('author_id', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('discriminator', models.CharField(max_length=5)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
