# Generated by Django 3.1.7 on 2021-04-07 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20)),
                ('author_id', models.CharField(default='0', max_length=20)),
                ('content', models.CharField(default='nan', max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 18, 32, 53, 511968))),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('avatar_url', models.CharField(default='nan', max_length=200)),
                ('name', models.CharField(default='nan', max_length=50)),
                ('discriminator', models.CharField(default='nan', max_length=5)),
                ('ghost', models.BooleanField(default=True)),
                ('nb_msg', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
            ],
        ),
    ]
