on:
  push:
    branches:
      - main
      - features
    
    pull_request:
      branches:
        - main
        - features

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 coverage
        python -m pip install -r requirements.txt
     - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. 
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Coverage report
      run: |
        coverage run manage.py test
        coverage report
    - name: Django testing
      run: |
        python manage.py test
